steps:
#Update the container image using kubectl set
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/site-vitrine'
  - 'frontend=europe-west3-docker.pkg.dev/coinwave/site-vitrine-repo/frontend:${_VERSION}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-prod'
  
substitutions:
    
    # Developers ONLY change (no change needed because it's production file. go to cloudbuild.yaml)
    _VERSION: latest
    
options:
    substitution_option: 'ALLOW_LOOSE'
