# Access the id_github file from Secret Manager, and setup SSH
steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --recurse-submodules
  - git@github.com:CoinWaveApp/SiteVitrine.git
  volumes:
  - name: 'ssh'
    path: /root/.ssh

availableSecrets:
  secretManager:
  - versionName: projects/coinwave/secrets/secret-name/versions/latest
    env: 'SSH_KEY'

- name: 'gcr.io/cloud-builders/git'
  args: ['clone','git@github.com:CoinWaveApp/SiteVitrine.git']
  
#Build the image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','${_ZONE}-docker.pkg.dev/${_PROJECT}/${_REPO_NAME}/${_DEPLOYMENTNAME}:${_VERSION}','.']

#Push the image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','${_ZONE}-docker.pkg.dev/${_PROJECT}/${_REPO_NAME}/${_DEPLOYMENTNAME}:${_VERSION}']
  
#Update the container image using kubectl set
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENTNAME}'
  - '${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  
substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: coinwave
    _ZONE: europe-west3-a
    _GKE_CLUSTER: cluster-dev
    
    #Repository Specific configuration. DevOps can change this settings
    _DEPLOYMENTNAME: site-vitrine
    _CONTAINERNAME: site-vitrine   
    _REPO_NAME: site-vitrine-repo
    
    # Developers ONLY change
    _VERSION: v1.0
    
options:
    substitution_option: 'ALLOW_LOOSE'
